app = "mtprotoproxy-o2ydfw"
primary_region = "sin"

[[services]]
internal_port = 443
protocol = "tcp"

  [[services.ports]]
  port = 443

  [[services.tcp_checks]]
  interval = "10s"
  timeout = "2s"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
